export const data = [
  {
    id: 1,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 1",
    description: "This is the description of Product 1.",
    rarity: "Base",
    chain: "eth",
    price: 1,
  },
  {
    id: 2,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 2",
    description: "This is the description of Product 2.",
    rarity: "Base",
    chain: "eth",
    price: 1,
  },
  {
    id: 3,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 3",
    description: "This is the description of Product 1.",
    rarity: "Base",
    chain: "eth",
    price: 1,
  },
  {
    id: 4,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 4",
    description: "This is the description of Product 2.",
    rarity: "Rare",
    chain: "bnb",
    price: 2,
  },
  {
    id: 5,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 5",
    description: "This is the description of Product 1.",
    rarity: "Rare",
    chain: "bnb",
    price: 2,
  },
  {
    id: 6,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 6",
    description: "This is the description of Product 2.",
    rarity: "Rare",
    chain: "bnb",
    price: 2,
  },
  {
    id: 7,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 7",
    description: "This is the description of Product 1.",
    rarity: "Epic",
    chain: "matic",
    price: 3,
  },
  {
    id: 8,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 8",
    description: "This is the description of Product 2.",
    rarity: "Epic",
    chain: "matic",
    price: 3,
  },
  {
    id: 9,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 9",
    description: "This is the description of Product 2.",
    rarity: "Epic",
    chain: "matic",
    price: 3,
  },
  {
    id: 10,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 10",
    description: "This is the description of Product 2.",
    rarity: "Legendary",
    chain: "sol",
    price: 3,
  },
  {
    id: 11,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 11",
    description: "This is the description of Product 2.",
    rarity: "Legendary",
    chain: "sol",
    price: 4,
  },
  {
    id: 12,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 12",
    description: "This is the description of Product 2.",
    rarity: "Legendary",
    chain: "sol",
    price: 4,
  },
  {
    id: 13,
    image: "https://source.unsplash.com/user/c_v_r/200x200",
    title: "Product 13",
    description: "This is the description of Product 2.",
    rarity: "Base",
    chain: "sui",
    price: 5,
  },
];
